// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_Server.Context;

namespace Movies_Server.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20181126200554_Initial_Database_Migration")]
    partial class Initial_Database_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movies_Server.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Director");

                    b.Property<string>("Genre");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new { Id = new Guid("12366b4e-3710-4851-9275-37a533710d2e"), Director = "Ridley Scott", Genre = "Sci-Fi, Thriller", Name = "Alien: Covenant" },
                        new { Id = new Guid("83a879ce-d6e6-4ff4-8a47-496226ae51bd"), Director = "Peter Jackson", Genre = "Adventure, Drama, Fantasy", Name = "The Lord Of The Rings" },
                        new { Id = new Guid("a831e1b9-555f-49e1-a226-fd81b6527f06"), Director = "Michael Cristofer", Genre = " Drama, Mystery, Romance", Name = "Original Sin" },
                        new { Id = new Guid("aec1fb29-dfc7-49d6-80b6-f00c8fb0cbe8"), Director = " Marc Forster", Genre = " Action, Adventure, Horror", Name = "World War Z" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
